[package]
name = "fragment"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[dependencies]
debug = { path="../debug" }
shared = { path="../shared" }
rand = "0.6.5"
