language: rust
rust:
- nightly
before_install:
  - cpp -v /dev/null
  - sudo apt-get install -y libc6-dev-i386 libc6-dev libgcc-5-dev
script:
  - cargo build --verbose --release --all
  - cargo test --verbose --all
  - cargo bench --verbose --all
