language: rust
rust:
- nightly
before_install:
  - sudo apt-get install -y libc6-dev-i386
script:
  - cargo build --verbose --release --all
  - cargo test --verbose --all
  - cargo bench --verbose --all
