[workspace]
members = [
    "src/core",
    "src/cparser",
    "src/ctoken",
    "src/lalr",
    "src/main",
    "src/parser",
    "src/preprocessor",
    "src/shared"
]

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
