[package]
name = "kieliconverter"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[dependencies]
cparser = { path="../cparser" }
ctoken = { path="../ctoken" }
kieliparser = { path="../kieliparser" }
