[package]
name = "parser"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]

[dependencies]
cparser = { path="../cparser" }
ctoken = { path="../ctoken" }
preprocessor = { path="../preprocessor" }
shared = { path="../shared" }
