[package]
name = "preprocessor"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[dependencies]
shared = { path="../shared" }
ctoken = { path="../ctoken" }
regex = "1.1.0"
