[package]
name = "kieliparser"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[dependencies]
fragment = { path="../fragment" }
lalr = { path="../lalr" }
kieliparser_procmacros = { path="../kieliparser_procmacros" }
shared = { path="../shared" }
