[package]
name = "lalr"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[lib]
crate-type = ["dylib"]
plugin = true

[dependencies]
debug = { path="../debug" }
rayon = "1.0.3"

