[package]
name = "kieli"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jaakko.hannikainen@solita.fi>"]

[dependencies]
lalr = { path="../lalr" }
lalr_runtime = { path="../lalr_runtime" }
preprocessor = { path="../preprocessor" }
shared = { path="../shared" }
