[package]
name = "kieli"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]

[dependencies]
parser = { path="../parser" }
preprocessor = { path="../preprocessor" }
shared = { path="../shared" }
clap = "2.32.0"
