[package]
name = "purkkasyntax"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[dependencies]
lalr = { path="../lalr" }
purkkasyntax_procmacros = { path="../purkkasyntax_procmacros" }
purkkatoken = { path="../purkkatoken" }
